name: Android Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk.zip
        unzip android-sdk.zip -d $HOME/android-sdk
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH
        mkdir -p $ANDROID_HOME/cmdline-tools
        yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses

    - name: Build with Gradle
      run: ./gradlew build