# 修改后的 GitHub Actions 工作流文件
name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      NDK_VERSION: 25.2.9519653
      BUILD_TOOLS_VERSION: "34.0.0"
      TARGET_API: "33"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate requirements.txt
        run: |
          echo "kivy==2.2.1" > requirements.txt
          echo "requests==2.31.0" >> requirements.txt
          echo "openssl" >> requirements.txt
          echo "pyjnius" >> requirements.txt
          echo "android" >> requirements.txt

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install core dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git zip unzip openjdk-8-jdk \
              python3-pip autoconf libtool pkg-config \
              zlib1g-dev libncurses5-dev libssl-dev

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install "urllib3<2" appdirs==1.4.4 cython==0.29.36
          pip install buildozer==1.5.0

      - name: Setup Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          rm commandlinetools-linux-*.zip

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-$TARGET_API" \
            "build-tools;$BUILD_TOOLS_VERSION" \
            "ndk;$NDK_VERSION"

      - name: Configure buildozer.spec
        run: |
          [ -f buildozer.spec ] || buildozer init
          sed -i '/^android.ndk = /c\android.ndk = 25.2.9519653' buildozer.spec
          sed -i '/^android.ndk_path = /c\android.ndk_path = $ANDROID_HOME/ndk/25.2.9519653' buildozer.spec
          sed -i '/^android.sdk_path = /c\android.sdk_path = $ANDROID_HOME' buildozer.spec
          sed -i '/^android.accept_sdk_license = /c\android.accept_sdk_license = True' buildozer.spec
          sed -i '/^#android.sdk_path/d' buildozer.spec  # 删除注释行

      - name: Initialize Python for Android
        run: |
          mkdir -p .buildozer/android/platform
          git clone --branch 2023.01.30 --depth 1 \
            https://github.com/kivy/python-for-android.git \
            .buildozer/android/platform/python-for-android

      - name: Build APK
        run: |
          buildozer -v android clean
          buildozer -v android debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: bin/*.apk