name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      NDK_VERSION: 25.2.9519653
      BUILD_TOOLS_VERSION: "34.0.0"
      TARGET_API: "33"
      P4A_TAG: "v2023.09.16"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate requirements.txt
        run: |
          cat > requirements.txt <<EOF
          kivy==2.2.1
          requests==2.31.0
          pyjnius==1.6.1
          appdirs==1.4.4
          cryptography==42.0.5
          EOF

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git zip unzip openjdk-8-jdk \
              python3-pip autoconf libtool pkg-config \
              zlib1g-dev libncurses5-dev \
              libssl-dev libffi-dev

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install "urllib3<2" cython==0.29.36 wheel==0.41.3
          pip install -r requirements.txt
          pip install buildozer==1.5.0

      - name: Configure buildozer.spec
        run: |
          [ -f buildozer.spec ] || buildozer init
          sed -i '/^source.dir/c\source.dir = .' buildozer.spec
          sed -i '/^version/c\version = 1.0.0' buildozer.spec
          sed -i '/^requirements/c\requirements = python3,kivy==2.2.1,requests==2.31.0,pyjnius,android' buildozer.spec
          sed -i '/^android.ndk_path/c\android.ndk_path = $ANDROID_HOME/ndk/$NDK_VERSION' buildozer.spec
          sed -i '/^android.sdk_path/c\android.sdk_path = $ANDROID_HOME' buildozer.spec

      - name: Setup Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          rm commandlinetools-linux-*.zip

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-$TARGET_API" \
            "build-tools;$BUILD_TOOLS_VERSION" \
            "ndk;$NDK_VERSION"

      - name: Initialize Python-for-Android
        run: |
          mkdir -p .buildozer/android/platform
          # 添加克隆重试机制
          for i in 1 2 3; do
            git clone --branch $P4A_TAG --depth 1 \
              https://github.com/kivy/python-for-android.git \
              .buildozer/android/platform/python-for-android && break || sleep 15
          done
          
          # 验证克隆结果
          if [ ! -d ".buildozer/android/platform/python-for-android" ]; then
            echo "错误：python-for-android 克隆失败"
            exit 1
          fi

          # 安装p4a依赖
          cd .buildozer/android/platform/python-for-android
          pip install -r requirements.txt

      - name: Pre-build cleanup
        run: |
          # 仅清理构建产物，保留必要文件
          rm -rf .buildozer/android/platform/build-*
          rm -rf .buildozer/android/app

      - name: Build APK
        run: |
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          buildozer -v android debug \
            --sdk_dir $ANDROID_HOME \
            --ndk_dir $ANDROID_HOME/ndk/$NDK_VERSION \
            --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            bin/*.apk
            .buildozer/android/platform/*.log