name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  HOME: ${{ github.workspace }}/.home
  ANDROID_SDK_ROOT: ${{ github.workspace }}/.android-sdk
  BUILD_DIR: ${{ github.workspace }}/.buildozer

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Initialize Environment
      run: |
        mkdir -p ${{ env.HOME }}
        mkdir -p ${{ env.ANDROID_SDK_ROOT }}
        mkdir -p ${{ env.BUILD_DIR }}
        chmod -R 755 ${{ github.workspace }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install System Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
            git \
            openjdk-11-jdk \
            zlib1g-dev \
            libssl-dev \
            libncurses5-dev \
            unzip

    - name: Install Build Tools
      run: |
        python -m pip install --user --upgrade pip
        python -m pip install --user cython==0.29.32 buildozer
        # 将用户级二进制目录加入 PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*.apk