name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git \
              zip \
              unzip \
              openjdk-8-jdk \
              python3-pip \
              autoconf \
              libtool \
              pkg-config \
              zlib1g-dev \
              libncurses5-dev \
              libtinfo6 \
              libncurses5 \
              libsqlite3-dev \
              libssl-dev \
              curl

      - name: Install Android Command Line Tools
        run: |
          # 下载并安装最新版命令行工具
          cd ${{ github.workspace }}
          mkdir -p $ANDROID_HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools-linux-*.zip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.19 buildozer==1.3.0

      - name: Configure buildozer.spec
        run: |
          sed -i '/^title = /c\title = RepairApp' buildozer.spec
          sed -i '/^package.name = /c\package.name = repairapp' buildozer.spec
          sed -i '/^package.domain = /c\package.domain = com.example' buildozer.spec
          sed -i '/^orientation = /c\orientation = portrait' buildozer.spec
          sed -i '/^requirements = /c\requirements = python3,kivy==2.0.0,requests,openssl,pyjnius,android' buildozer.spec
          sed -i '/^android.permissions = /c\android.permissions = INTERNET' buildozer.spec
          sed -i '/^android.api = /c\android.api = 33' buildozer.spec
          sed -i '/^android.ndk = /c\android.ndk = 25b' buildozer.spec
          sed -i '/^#android.accept_sdk_license = /c\android.accept_sdk_license = True' buildozer.spec

      - name: Setup Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # 安装必要组件
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.1" \
            "ndk;25.2.9519653"

      - name: Build Android APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: repair-app
          path: bin/*.apk
          retention-days: 5