name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      NDK_VERSION: 25.2.9519653
      BUILD_TOOLS_VERSION: "34.0.0"
      TARGET_API: "33"
      P4A_COMMIT: "e155baf"  # 使用明确的commit hash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git zip unzip openjdk-8-jdk \
              python3-pip autoconf libtool pkg-config \
              zlib1g-dev libncurses5-dev \
              libssl-dev libffi-dev

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install "urllib3<2" cython==0.29.36 wheel==0.41.3
          pip install kivy==2.2.1 requests==2.31.0 pyjnius==1.6.1
          pip install buildozer==1.5.0

      - name: Configure buildozer.spec
        run: |
          cat > buildozer.spec <<EOF
          [app]
          title = RepairApp
          package.name = repairapp
          package.domain = com.example
          source.dir = .
          version = 1.0.0
          requirements = python3,kivy==2.2.1,requests==2.31.0,pyjnius,android
          android.sdk_path = $ANDROID_HOME
          android.ndk_path = $ANDROID_HOME/ndk/$NDK_VERSION
          android.build_tools = $BUILD_TOOLS_VERSION
          android.api = $TARGET_API
          android.ndk = $NDK_VERSION
          android.minapi = 21
          android.accept_sdk_license = True
          p4a.branch = master
          log_level = 2
          EOF

      - name: Setup Android SDK
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools/latest
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-$TARGET_API" \
            "build-tools;$BUILD_TOOLS_VERSION" \
            "ndk;$NDK_VERSION"

      - name: Initialize Python-for-Android
        run: |
          mkdir -p .buildozer/android/platform
          git clone https://github.com/kivy/python-for-android.git .buildozer/android/platform/python-for-android
          cd .buildozer/android/platform/python-for-android
          git checkout $P4A_COMMIT
          pip install -r requirements.txt

      - name: Build APK
        timeout-minutes: 30
        run: |
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          buildozer android clean
          buildozer -v android debug \
            --sdk_dir $ANDROID_HOME \
            --ndk_dir $ANDROID_HOME/ndk/$NDK_VERSION \
            --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            bin/*.apk
            .buildozer/android/platform/*.log