name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_HOME: /usr/lib/android-sdk
      ANDROID_SDK_ROOT: /usr/lib/android-sdk
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git \
              zip \
              unzip \
              openjdk-8-jdk \
              python3-pip \
              autoconf \
              libtool \
              pkg-config \
              zlib1g-dev \
              libncurses5-dev \
              libtinfo6 \
              libncurses5 \
              libsqlite3-dev \
              libssl-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.19 buildozer==1.3.0

      - name: Initialize Buildozer
        run: |
          buildozer init
          # 更新buildozer.spec配置
          sed -i '/^#title = My Application/c\title = RepairApp' buildozer.spec
          sed -i '/^package.name = myapp/c\package.name = repairapp' buildozer.spec
          sed -i '/^package.domain = org.test/c\package.domain = com.example' buildozer.spec
          sed -i '/^#orientation = portrait/c\orientation = portrait' buildozer.spec
          sed -i '/^requirements = /c\requirements = python3,kivy==2.0.0,requests,openssl,pyjnius,android' buildozer.spec
          sed -i '/^#android.permissions = /c\android.permissions = INTERNET' buildozer.spec
          sed -i '/^#android.api = /c\android.api = 33' buildozer.spec
          sed -i '/^#android.ndk = /c\android.ndk = 25b' buildozer.spec

      - name: Setup Android SDK
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses

      - name: Build Android APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: repair-app
          path: bin/*.apk
          retention-days: 5