name: Android Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git unzip openjdk-11-jdk

      - name: Install Buildozer and Cython
        run: |
          pip install buildozer cython==0.29.19

      - name: Setup Android SDK/NDK
        run: |
          mkdir -p ~/.android/cmdline-tools
          wget -qO cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip cmdline-tools.zip -d ~/.android/cmdline-tools
          mv ~/.android/cmdline-tools/cmdline-tools ~/.android/cmdline-tools/latest

          echo "ANDROID_SDK_ROOT=$HOME/.android" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/.android/cmdline-tools/latest/bin:$HOME/.android/platform-tools:$HOME/.android/ndk/23.1.7779620/bin" >> $GITHUB_ENV

          sdkmanager --licenses accept-all
          sdkmanager "platforms;android-33" "build-tools;34.0.0" "ndk;23.1.7779620"

      - name: Fix Buildozer Paths
        run: |
          sed -i "s|/home/runner/work/.*android-sdk|$HOME/.android|g" buildozer.spec
          sed -i "s|/home/runner/work/.*ndk/.*|$HOME/.android/ndk/23.1.7779620|g" buildozer.spec

      - name: Validate Buildozer Spec
        run: cat buildozer.spec | grep -E "^android\.sdk_path|^android\.ndk_path"

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/app-debug.apk