name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ANDROID_SDK_ROOT: ${{ github.workspace }}/.android-sdk
  BUILD_DIR: ${{ github.workspace }}/.buildozer

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v4

    - name: Setup Android SDK Path
      run: |
        mkdir -p ${{ env.ANDROID_SDK_ROOT }}
        chmod 777 ${{ env.ANDROID_SDK_ROOT }}
        echo "sdk.dir=${{ env.ANDROID_SDK_ROOT }}" > local.properties

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install system deps
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
            git \
            openjdk-11-jdk \
            zlib1g-dev \
            libssl-dev \
            libncurses5-dev \
            unzip

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.32 buildozer

    - name: Build APK
      run: |
        buildozer android debug
        ls -l ${{ env.BUILD_DIR }}/android/platform

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk