name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # 明确指定 20.04 LTS
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install system deps
      run: |
        sudo apt-get update -y  # 强制更新源
        sudo apt-get install -y \
            git \
            openjdk-11-jdk \
            zlib1g-dev \
            libssl-dev \
            libncurses5-dev \
            python3-pip \
            unzip

    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.android/android-sdk-license
        yes | sdkmanager --licenses || true

    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        pip install cython==0.29.32 buildozer

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk