name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      
    steps:
      - uses: actions/checkout@v4

      - name: Generate requirements.txt
        run: |
          cat << EOF > requirements.txt
          kivy==2.2.1
          requests==2.31.0
          openssl
          pyjnius
          android
          EOF

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install system deps
        run: |
          sudo apt-get install -y \
              git zip unzip openjdk-8-jdk \
              python3-pip autoconf libtool pkg-config \
              zlib1g-dev libncurses5-dev libtinfo6 \
              libsqlite3-dev libssl-dev libgl1-mesa-dev \
              libgles2-mesa-dev

      - name: Setup Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          rm commandlinetools-linux-*.zip

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" "platforms;android-33" \
            "build-tools;34.0.0" "ndk;25.2.9519653"

      - name: Init Python for Android
        run: |
          mkdir -p .buildozer/android/platform
          git clone --branch 2023.08.04 \
            https://github.com/kivy/python-for-android.git \
            .buildozer/android/platform/python-for-android

      - name: Build APK
        run: |
          buildozer init
          sed -i '/^android.ndk = /c\android.ndk = 25.2.9519653' buildozer.spec
          sed -i '/^android.ndk_path = /c\android.ndk_path = $ANDROID_HOME/ndk/25.2.9519653' buildozer.spec
          buildozer -v android debug