name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # 延长超时时间

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            git \
            openjdk-11-jdk \
            zlib1g-dev \
            libssl-dev \          # 新增 OpenSSL 支持
            libncurses5-dev

    - name: Accept Android licenses  # 关键修复
      run: |
        mkdir -p ~/.android
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > ~/.android/android-sdk-license
        yes | sdkmanager --licenses || true  # 强制接受许可

    - name: Install Buildozer with Cython
      run: |
        pip install --upgrade pip
        pip install cython==0.29.32  # 指定兼容版本
        pip install buildozer

    - name: Build APK with retry  # 增加重试机制
      run: |
        for i in {1..3}; do
          buildozer android debug && break
          sleep 10
        done

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk