name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # 核心路径配置
  HOME: ${{ github.workspace }}/.home  # 彻底重定向用户目录
  ANDROID_SDK_ROOT: ${{ github.workspace }}/.android-sdk
  ANDROID_NDK_HOME: ${{ github.workspace }}/.android-ndk
  BUILD_DIR: ${{ github.workspace }}/.buildozer

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Initialize Environment
      run: |
        # 强制创建所有关键目录
        mkdir -p ${{ env.HOME }}
        mkdir -p ${{ env.ANDROID_SDK_ROOT }}
        mkdir -p ${{ env.ANDROID_NDK_HOME }}
        mkdir -p ${{ env.BUILD_DIR }}
        
        # 递归设置权限（必须使用755模式）
        chmod -R 755 ${{ github.workspace }}
        
        # 生成Buildozer强制路径配置文件
        echo "[buildozer]" > buildozer.cfg
        echo "android.sdk_path = ${{ env.ANDROID_SDK_ROOT }}" >> buildozer.cfg
        echo "android.ndk_path = ${{ env.ANDROID_NDK_HOME }}" >> buildozer.cfg

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install System Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
            git \
            openjdk-11-jdk \
            zlib1g-dev \
            libssl-dev \
            libncurses5-dev \
            unzip

    - name: Install Build Tools
      run: |
        python -m pip install --user --upgrade pip
        python -m pip install --user cython==0.29.32 buildozer

    - name: Build APK
      run: |
        export PATH="${{ github.workspace }}/.local/bin:$PATH"
        # 强制使用自定义配置
        buildozer --config buildozer.cfg android debug

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*.apk