name: Android CI

env:
  # 核心路径定义
  WORKSPACE: ${{ github.workspace }}
  PYTHON_USER_BASE: ${{ github.workspace }}/.python_packages
  ANDROID_SDK_ROOT: ${{ github.workspace }}/.android-sdk
  ANDROID_NDK_HOME: ${{ github.workspace }}/.android-ndk

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Initialize Environment
      run: |
        # 创建隔离目录
        mkdir -p ${{ env.PYTHON_USER_BASE }}
        mkdir -p ${{ env.ANDROID_SDK_ROOT }}
        mkdir -p ${{ env.ANDROID_NDK_HOME }}
        
        # 递归设置权限（关键）
        sudo chmod -R 777 ${{ github.workspace }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install System Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
            git \
            openjdk-11-jdk \
            zlib1g-dev \
            libssl-dev \
            libncurses5-dev \
            unzip

    - name: Install Build Tools
      run: |
        # 显式定义Python用户安装路径
        export PYTHONUSERBASE=${{ env.PYTHON_USER_BASE }}
        export PATH="$PYTHONUSERBASE/bin:$PATH"
        
        # 安装并验证
        python -m pip install --user --upgrade pip | tee pip_install.log
        python -m pip install --user cython==0.29.32 buildozer | tee buildozer_install.log
        
        # 检查安装结果
        if [ ! -f "$PYTHONUSERBASE/bin/buildozer" ]; then
          echo "❌ Buildozer安装失败！"
          cat pip_install.log buildozer_install.log
          exit 1
        fi
        
        # 持久化路径
        echo "$PYTHONUSERBASE/bin" >> $GITHUB_PATH

    - name: Build APK
      run: |
        # 使用绝对路径调用
        ${{ env.PYTHON_USER_BASE }}/bin/buildozer \
          --sdk_dir ${{ env.ANDROID_SDK_ROOT }} \
          --ndk_dir ${{ env.ANDROID_NDK_HOME }} \
          android debug

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*.apk