name: Android Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          # 强制创建虚拟环境（解决Python版本隔离问题）
          virtual-environment: true

      - name: Initialize Build Environment
        run: |
          # 创建独立构建目录
          mkdir -p build_env
          cd build_env

      - name: Install Buildozer in Isolated Environment
        run: |
          # 在独立目录安装Buildozer（避免污染系统环境）
          python3 -m venv venv
          source venv/bin/activate
          pip install buildozer cython==0.29.19

      - name: Configure Android SDK/NDK Paths
        run: |
          # 下载并配置Android工具链
          mkdir -p ~/.android/cmdline-tools
          wget -qO cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip cmdline-tools.zip -d ~/.android/cmdline-tools
          mv ~/.android/cmdline-tools/cmdline-tools ~/.android/cmdline-tools/latest

          # 强制设置全局环境变量（关键修改）
          export ANDROID_SDK_ROOT=$HOME/.android
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/ndk/23.1.7779620/bin
          # 导出到GitHub Actions环境
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV

          # 验证环境变量生效
          sdkmanager --version

      - name: Accept Android Licenses
        run: |
          sdkmanager --licenses accept-all

      - name: Update Buildozer Spec File
        run: |
          # 使用绝对路径覆盖原有配置（关键修改）
          sed -i "s|android.sdk_path = .*|android.sdk_path = $ANDROID_SDK_ROOT|" buildozer.spec
          sed -i "s|android.ndk_path = .*|android.ndk_path = $ANDROID_SDK_ROOT/ndk/23.1.7779620|" buildozer.spec
          sed -i "s|p4a.sdk = .*|p4a.sdk = 33|" buildozer.spec
          cat buildozer.spec

      - name: Build APK with Verbose Logging
        run: |
          # 在独立虚拟环境中执行构建（关键修改）
          cd build_env
          source venv/bin/activate
          buildozer -v android debug

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build_env/bin/app-debug.apk