name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      NDK_VERSION: 25.2.9519653
      BUILD_TOOLS_VERSION: "34.0.0"
      TARGET_API: "33"
      P4A_TAG: "v2023.09.16"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate requirements.txt
        run: |
          cat > requirements.txt <<EOF
          kivy==2.2.1
          requests==2.31.0
          openssl
          pyjnius
          android
          appdirs==1.4.4
          setuptools==68.2.2  # 新增关键依赖
          EOF

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              git zip unzip openjdk-8-jdk \
              python3-pip autoconf libtool pkg-config \
              zlib1g-dev libncurses5-dev libssl-dev \
              libffi-dev  # 新增系统依赖

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install "urllib3<2" cython==0.29.36 wheel==0.41.3
          pip install -r requirements.txt
          pip install buildozer==1.5.0

      - name: Initialize buildozer.spec
        run: |
          [ -f buildozer.spec ] || buildozer init
          sed -i '/^source.dir/c\source.dir = .' buildozer.spec
          sed -i '/^version/c\version = 1.0.0' buildozer.spec
          sed -i '/^requirements/c\requirements = python3,kivy==2.2.1,requests==2.31.0,openssl,pyjnius,android,appdirs,setuptools' buildozer.spec

      - name: Configure Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          cd $ANDROID_HOME
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-*.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          rm commandlinetools-linux-*.zip

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-$TARGET_API" \
            "build-tools;$BUILD_TOOLS_VERSION" \
            "ndk;$NDK_VERSION"

      - name: Configure NDK paths
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$NDK_VERSION" >> $GITHUB_ENV
          echo "NDK_ROOT=$ANDROID_HOME/ndk/$NDK_VERSION" >> $GITHUB_ENV
          echo "export ANDROID_NDK_HOME" >> $BASH_ENV

      - name: Initialize Python-for-Android
        run: |
          mkdir -p .buildozer/android/platform
          git clone --branch $P4A_TAG --depth 1 \
            https://github.com/kivy/python-for-android.git \
            .buildozer/android/platform/python-for-android
          
          # 修复p4a的依赖问题
          cd .buildozer/android/platform/python-for-android
          pip install -r requirements.txt

      - name: Clean build environment
        run: |
          rm -rf .buildozer/android/platform/build-*
          rm -rf ~/.local/share/python-for-android/

      - name: Build APK
        run: |
          # 强制设置环境变量
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          export USE_SYSTEM_PYTHON=1
          
          buildozer -v android clean all
          buildozer -v android debug \
            --sdk_dir $ANDROID_HOME \
            --ndk_dir $ANDROID_HOME/ndk/$NDK_VERSION \
            --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            bin/*.apk
            .buildozer/*.log